### ISSUE TITLE
pro!coin and pro!toss

### ISSUE THREAD

**Issue by simon-tiger** [Andy-Python-Programmer/pro-bot#1]
We did a poll in my bot test server for what the `pro!coin` command should do:

🟠 Outputs heads or tails randomly.
❓ Lets you predict the output, which is heads or tails randomly. If you're right, you win, if not, you lose.

The overwhelming winner was ❓, but I still felt like we needed 🟠, because we already have `pro!roll` and `pro!random`. So now my idea is for `pro!coin` to be 🟠, and `pro!toss` to be ❓.

So, `pro!coin` should just send a message with `The answer is heads!` or `The answer is tails!` randomly, or something like that. `pro!toss` should be more of a game. It should set up an embed with something like:

> **Let's play Toss!**
>
> You can react with heads or tails to predict a coinflip. If you get it right, you win! If not, you lose.

With emoji reactions for 🇭 or 🇹. The player should then be able to react with 🇭 or 🇹 to play the game.

**Comment by Andy-Python-Programmer** [comment]
Hi @simon-tiger thanks for submitting your first issue! I will add this feature in upcoming days!

**Comment by Andy-Python-Programmer** [comment]
Added `pro!toss`

**Comment by Andy-Python-Programmer** [comment]
Added `pro!coin`
